apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sContainerLimits
metadata:
  name: container-must-have-limits
spec:
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment", "StatefulSet", "DaemonSet"]
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - "demo-app"
    excludedNamespaces:
      - "kube-system"
      - "gatekeeper-system"
  parameters:
    cpu: "2000m"
    memory: "2Gi"
